### ISSUE TITLE
README: Add animated gif + proposed refinements

### ISSUE THREAD

**Issue by luzpaz** [easyw/Manipulator#1]
Added screenshot ![manipulatorwb-preview](https://user-images.githubusercontent.com/4140247/31278727-273cd0a0-aa74-11e7-8ec7-d37ee6fc52c2.gif)
+ refinements

(FYI needed to open issue since I had to upload the GIF to GitHub)
Thanks for this cool feature!

**Comment by easyw** [comment]
Hi @luzpaz 
thx for your contribution... 
ATM I'm refining the WB to manipulate App::Part hierarchical and Body objects... after that I will add some gif to explain a bit the WB features 😸
