### ISSUE TITLE
Does ManipulatorWB have a logo/icon

### ISSUE THREAD

**Issue by luzpaz** [easyw/Manipulator#15]
I'd like to add to https://freecadweb.org/wiki/Template:DevWorkbenches

**Comment by easyw** [comment]
Hi @luzpaz 
Thanks for doing this 😄 
The icon for WBs is the one used to display the WB in FC
In Manipulator WB is:
https://github.com/easyw/Manipulator/blob/master/Resources/icons/Manipulator-icon.svg
It is assigned in InitGui.py
https://github.com/easyw/Manipulator/blob/master/InitGui.py

**Comment by easyw** [comment]
PS there is also this page 
https://freecadweb.org/wiki/External_workbenches
linked by this
https://freecadweb.org/wiki/Workbenches

**Comment by easyw** [comment]
@luzpaz 
Would you please add also my [Defeaturing WB](https://github.com/easyw/Defeaturing_WB) in that list?

**Comment by easyw** [comment]
here the icons for:
StepUp WB and StepUp sourgeforce site
https://github.com/easyw/kicadStepUpMod/blob/master/Resources/icons/kicad-StepUp-tools-WB.svg
and for Defeaturing WB
https://github.com/easyw/Defeaturing_WB/blob/master/Resources/icons/Defeaturing-icon.svg

**Comment by luzpaz** [comment]
Done. 
@easyw can you please take care of the following:  

1. on https://www.freecadweb.org/wiki/Template:DevWorkbenches there are 2 kicads (one of them links to sourceforge Whats the deal?
2. kicad stepup doesn't have a dedicated wiki page. Yorik wants each workbench to have a wiki page. Can you create one for it ?

**Comment by easyw** [comment]
> 1. on https://www.freecadweb.org/wiki/Template:DevWorkbenches there are 2 kicads (one of them links to sourceforge Whats the deal?

The sourceforge was the first place to hold the Macro, later on I developed the WB and at GH there is the latest code.
Still sourceforge has a release that can be updated by the FC Addons and it is maintained for consistence. (I can get also a detailed download report there).
You can put just the kicadStepUpMod WB at the FC page.
Thx again
Maurice

**Comment by luzpaz** [comment]
Should I remove the link so people aren't confused ?

**Comment by luzpaz** [comment]
Done!
