### ISSUE TITLE
Undo/redo

### ISSUE THREAD

**Issue by DeepSOIC** [easyw/Manipulator#16]
Hi!
Why is Aligner using its own internal undo/redo system?

Using undo/redo in FreeCAD is very easy. Just add `App.ActiveDocument.openTransaction('title')` before doing anything, `App.ActiveDocument.abortTransaction()` if canceled (freecad unrolls all changes), and `App.ActiveDocument.commitTransaction()` when all changes are applied.

**Comment by DeepSOIC** [comment]
https://github.com/easyw/Manipulator/pull/17 as a demo

**Comment by easyw** [comment]
thanks a lot, I didn't know about openTransaction
I will have a look at 😄 
Maurice

**Comment by easyw** [comment]
Done :)
Thx
