### ISSUE TITLE
Caliper dialog does not deploy

### ISSUE THREAD

**Issue by EdgarJRobles** [easyw/Manipulator#22]
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16117 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: dbb4cc6415bac848a294f03b80f65e888d531742
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

The Manipulator workbench run property but this not deploy Caliper dialog

this is what report view print 
"Manipulator WB Activated(v 1.3.2)
Caliper version 1.5.2
Caliper
closed
Caliper active :)
"

**Comment by easyw** [comment]
hi @EdgarJRobles 
ATM I cannot test it on Win... do you have a dual monitor?

**Comment by easyw** [comment]
@EdgarJRobles 
would you please try to remove and re-install Manipulator through the FC Tool Addons manager menu to see if this new commit could solve your issue?
I've added a menu under Manipulator WB to Reset Widgets positions...
![centering-widgets](https://user-images.githubusercontent.com/3032347/63445624-03f3cc80-c439-11e9-9df1-7f6fa9960f8f.png)

**Comment by EdgarJRobles** [comment]
> @EdgarJRobles
> would you please try to remove and re-install Manipulator through the FC Tool Addons manager menu to see if this [new commit](https://github.com/easyw/Manipulator/commit/a7f0f1eb59ba7cee37732b279ecab7b3bc08a051) could solve your issue?
> I've added a menu under Manipulator WB to Reset Widgets positions...
> ![centering-widgets](https://user-images.githubusercontent.com/3032347/63445624-03f3cc80-c439-11e9-9df1-7f6fa9960f8f.png)

Nice!
Centering widget button did the job

Thank you!

**Comment by EdgarJRobles** [comment]
You right about the screen.
I was making assemblies with a dual monitor in FreeCAD 1 week ago.
This is what i am working on..
![Job project](https://user-images.githubusercontent.com/13512639/63465714-7360c080-c427-11e9-87e3-a6361604d3b2.jpg)

**Comment by easyw** [comment]
Thx for the feedback... Nice job though!
