### ISSUE TITLE
Unable to manipulate App::Part and Body objects

### ISSUE THREAD

**Issue by guillert** [easyw/Manipulator#28]
I don't know if i am doing something bad, but I am Unable to move, align or anything else with any linked Part or body.

Thank you, have a nice day.

**Comment by easyw** [comment]
@guillert 
would you please add a sample FC file (zipped)?

**Comment by guillert** [comment]
Ok,

[https://mega.nz/file/0R1XzBgB#anQFtccI0H7eXklOsFFStn9gCscmgWc-R_BwZAybTfU](url)

I'll also write the version and the errors.

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.20477 (Git)
Build type: Release
Branch: master
Hash: 7d8ab175a68e476427e6e337fe3099b52da49dc8
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Spanish/Spain (es_ES)

Aligner version 1.8.6
position set float/532/370/288/318
Aligner active :)
Align clicked
centering on Center of Mass
Centering and aligning Planes
position written float/1448/281/288/318
111
number of objects: 2
obj: Mirrored
Placement: Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(0,0,90)]
obj: Mirrored
Placement: Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(0,0,0)]
j= 0
len selEx 2
Placement [Pos=(0,2.20446e-16,10), Yaw-Pitch-Roll=(180,0,1.27222e-14)]
Label : Mirrored
Name  : Mirrored
Center Face Binder 0 Vector (-60.0, -25.0, 10.0)
Center Face Binder bb 0 Vector (-59.98946125143618, -25.0, 10.000000000000005)
Body
Link
Link
Base App::Link
['Body', 'Link', 'Link']
Traceback (most recent call last):
  File "C:\Users\Guille\AppData\Roaming\FreeCAD\Mod\Manipulator\Aligner.py", line 884, in onAlign
    Align(normal,type,mode,cx,cy,cz)
  File "C:\Users\Guille\AppData\Roaming\FreeCAD\Mod\Manipulator\Aligner.py", line 1971, in Align
    listSorted=get_sorted_list (ob)
  File "C:\Users\Guille\AppData\Roaming\FreeCAD\Mod\Manipulator\Aligner.py", line 1459, in get_sorted_list
    if len(ap.InListRecursive) < lvl:
AttributeError: 'NoneType' object has no attribute 'InListRecursive'

**Comment by easyw** [comment]
@guillert 
thanks for the sample file.
I see the issue and I will have a look at it.
ATM very little support has been done for the recent introduced Link features... I will try to improve it for Manipulator WB.

**Comment by guillert** [comment]
Thank you very much, keep me updated ;D

**Comment by easyw** [comment]
@guillert
it should be fine now https://github.com/easyw/Manipulator/commit/48b9607ef146faf9335f3c4a79174f380226baaa
could you please update the WB and test it?

**Comment by guillert** [comment]
Yeah, it's working. Thank you.

**Comment by yashpalgoyal1304** [comment]
i am still having problems with aligning the bodys whenever they go inside a part. tried with only linked things, but i think this applies to non-linked things as well.
