### ISSUE TITLE
Calipers broken with latest daily build

### ISSUE THREAD

**Issue by macdroid53** [easyw/Manipulator#29]
Any attempt to use clipers:

`11:50:23  starting!
11:50:28  draft: deprecation warning: Do not use getDefaultColor("ui") anymore - use getDefaultColor("line") instead.
11:50:28  Traceback (most recent call last):
  File "/home/mac/.FreeCAD/Mod/Manipulator/Caliper.py", line 485, in addSelection
    PC=mDraft.makePoint(pnt[0],pnt[1],pnt[2])
  File "/home/mac/.FreeCAD/Mod/Manipulator/oDraft.py", line 2937, in makePoint
    color = FreeCADGui.draftToolBar.getDefaultColor('ui')
  File "/usr/share/freecad-daily/Mod/Draft/DraftGui.py", line 1690, in getDefaultColor
    r = float(self.color.red()/255.0)
<class 'AttributeError'>: 'DraftToolBar' object has no attribute 'color'
`
`OS: Ubuntu 20.04.1 LTS (XFCE/ubuntustudio)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Branch: unknown
Hash: cdc01cb20cfa74079c45b9dc2dab81e3248b2aa5
Python version: 3.8.5
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.3.0
Locale: English/United States (en_US)
`

**Comment by donovaly** [comment]
I have the same problem:

`draft: deprecation warning: Do not use getDefaultColor("ui") anymore - use getDefaultColor("line") instead.
 Traceback (most recent call last):

  File "C:\Users\USti\AppData\Roaming\FreeCAD\Mod\Manipulator\Caliper.py", line 601, in addSelection
    PC=mDraft.makePoint(P1[0],P1[1],P1[2])
  File "C:\Users\USti\AppData\Roaming\FreeCAD\Mod\Manipulator\oDraft.py", line 2937, in makePoint
    color = FreeCADGui.draftToolBar.getDefaultColor('ui')
  File "D:\FreeCAD-build\Mod\Draft\DraftGui.py", line 1690, in getDefaultColor
    r = float(self.color.red()/255.0)
<class 'AttributeError'>: 'DraftToolBar' object has no attribute 'color'`

**Comment by macdroid53** [comment]
I was able to fix  the one one line 2937. But then it failed when it tried to use the FreeCADGui.draftToolbar.linewidth. it says there is no such , but the api docs disagree and I haven't gotten any replies in the forum on that.

**Comment by easyw** [comment]
@donovaly @macdroid53 
it seems that recently commit have changed DraftToolBar attributes...
I posted an issue @ FC forum
https://forum.freecadweb.org/viewtopic.php?f=23&t=52133

**Comment by easyw** [comment]
@donovaly @macdroid53 I'm closing this as solved... feel free to reopn it in case of need.

**Comment by macdroid53** [comment]
Yes, but yorik's commit fixed the missing attributes, not the deprecation warning that my pull request fixes.

**Comment by donovaly** [comment]
Thanks for the fix. However, why does manipulator rely on deprecated code?

**Comment by macdroid53** [comment]
The code was only deprecated a few days ago. The deprecation error was coming from yoriks commit saying the object had changed.

**Comment by donovaly** [comment]
> The code was only deprecated a few days ago. 

Ah, OK then.
