### ISSUE TITLE
Transparency sticks (bug)

### ISSUE THREAD

**Issue by yashpalgoyal1304** [easyw/Manipulator#36]
So, i clicked some object, chose XRay mode in this manipulator WB's align tool, and then chose some other object etc etc, and exited the align tool. That is, did not complete the action which the xray toggle was waiting for.

The result was that the transparency got applied to the body. And then i mistakenly saved the file 🤦 

I check all things i could thought of:
* checking the transparency of body: was set to 0
* searching for "xray" or "transparent" like terms in launcher add on: nothing found
* checking python console to see what the xray toggle of this align tool does : any activity of this addon doesnt show up on the python console
* closing the document and reopening: nothing
* closing freecad and reopening: still nothing
* uninstalled this manipulator addon: still nothing

+ moving up down the feature tree: the older feature was showing opaque (some hope :)
+ changing the body's view > Disaplay mode to Tip (from default's through): that made it opaque in current viewerport, but it still showed transparent in the document in which it was linked
+ then finally, i changed the transparency of the body (which was already set to zero), and set it back to zero, only this helped in restoring all the way - in current viewerport, upto the tip of feature tree, and in linked documents as well

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 +99 (Git)
Build type: Release
Branch: Branch_0.19.3
Hash: 6530e364184ce05ccff39501e175cf2237e6ee4b
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

```

**Comment by luzpaz** [comment]
@easyw ping
