### ISSUE TITLE
Caliper tool crashes

### ISSUE THREAD

**Issue by ivizot** [easyw/Manipulator#5]
When I finish selecting e.g. two faces for distance measurement, it plots the "dimension" and then shows the error:

Traceback (most recent call last):
  File "/home/ivizot/.FreeCAD/Mod/Manipulator/Caliper.py", line 417, in addSelection
    Draft.autogroup(dim)
<type 'exceptions.AttributeError'>: 'module' object has no attribute 'autogroup'

I suppose that is somehow related to the indication of the distance near the line showing measurement...
![screenshot from 2017-11-08 16-17-56](https://user-images.githubusercontent.com/25691918/32551088-680fa2e2-c4a0-11e7-8bf1-5aecbc084f79.png)

**Comment by easyw** [comment]
Hi @ivizot 
would you mind to attach a FC file with this issue? And would you post also which Faces are causing this issue?
I would also need your FC info data...
Maurice

**Comment by easyw** [comment]
And that would be nice to be posted at FC forum

https://forum.freecadweb.org/viewtopic.php?f=9&t=24742

**Comment by easyw** [comment]
ok, I found it ... it is an issue only in FC0.16 that I don't use very often... It is fixed now... I'm closing it
