### ISSUE TITLE
Manipulator blurb on FC 0.17 release page

### ISSUE THREAD

**Issue by luzpaz** [easyw/Manipulator#6]
https://www.freecadweb.org/wiki/Release_notes_017#Additional_Modules
A short blurb some highlights of what it does and a link to more details? This way people know more about it? Thoughts ?

**Comment by luzpaz** [comment]
@easyw ping

**Comment by easyw** [comment]
@luzpaz 
I did it... should I also add some info on kicad StepUp?

**Comment by luzpaz** [comment]
I transferred it to https://www.freecadweb.org/wiki/Release_notes_0.17#Additional_Modules and yes, feel free to add kicad StepUp there as well :smile:
