### ISSUE TITLE
move multiple pieces

### ISSUE THREAD

**Issue by morganrallen** [easyw/Manipulator#7]
It would be great to be able to move multiple objects at the same time.

Ideally, to be able to

1) select objects from hierarchical view
2) use ctrl/shift to select multiple object
3) select and manipulate groups in hierarchy

Great tool, it's easier to use than Draft but slow because I can only seem to do one thing at a time.

**Comment by easyw** [comment]
Hi @morganrallen 
Manipulator can move a single object or all the objects in a hierarchy, by selecting an internal face/edge.
The implemented logic for multiple objects is based on the top level container, where instead the the direction for the movement is determined by a single object edge/face.
<img src="https://www.freecadweb.org/wiki/images/f/f4/Manipulator-WB-Mover-with-App_Part%26Body.gif">

Part Design Next container is the reference container used by the Mover, and this WB in general is aimed for assembly parts without adding constraints.
You can find some tutorial here
https://github.com/easyw/FreeCAD-tutorials
<img src="https://raw.githubusercontent.com/easyw/FreeCAD-tutorials/master/align-arduino-pcb-to-a-case.gif">

**Comment by morganrallen** [comment]
Ok thanks, I'll have another look
